[build-system]
requires = ["setuptools>=45", "wheel", "cmake>=3.10"]
build-backend = "setuptools.build_meta"

[project]
name = "TS2CG"
version = "2.0"
description = "TS2CG: converts triangulated surfaces to coarse-grained membrane models"
requires-python = ">=3.6"
authors = [
    {name = "Weria Pezeshkian", email = "weria.pezeshkian@nbi.ku.dk"},
    {name = "Fabian Schuhmann", email = "fabian.schuhmann@nbi.ku.dk"},
    {name = "Jan Stevens", email = "j.a.stevens@rug.nl"},
]
license = {file = "LICENSE"}
dependencies = ["numpy", "networkx", "scipy","matplotlib", "MDAnalysis", "vtk"]

[tool.setuptools]
packages = ["TS2CG"]
package-dir = {"" = "."}

[project.scripts]
TS2CG = "TS2CG.run_modules:main"
